
exclude:
  - "README.md"
  - "LICENSE.md"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: GDG Toulouse
subtitle: "L'association des professionnels liés aux technologies"
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "http://www.gdgtoulouse.fr/" # the base hostname & protocol for your site
baseurl: ""

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-37717223-4"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

gems:
  - jekyll-feed
